### ISSUE TITLE
Extension's settings page erroneously shows on some pages

### ISSUE THREAD

**Issue by Lesik** [jcoyle37/URL-Throttler-2024#1]
Thanks for porting this extension to Firefox! It is very useful for developing SPA apps.

I noticed a weird behavior: When visiting some websites, the extension's settings page shows instead. Even if the "Enabled" checkbox is unchecked in the extension's settings and there are no throttled URLs added. Only disabling the extension entirely through the Firefox extension manager lets me access the website again.

So far, I have (by chance) discovered this behavior on the websites below. It is 100% reproducible in Firefox version 127.0.2 and URL Throttler version 1.0. Notice how the extension's settings page is styled differently depending on the page triggering it, which suggest that the page's original CSS is loaded as well.

- #### https://fedoraproject.org/

  ![Screenshot of Firefox opening fedoraproject.org, but showing the extension's settings page instead](https://github.com/jcoyle37/URL-Throttler-2024/assets/2021487/d5b6109a-ad09-4bc3-8ac6-6668198b8421)

- #### https://schedule.mozillafestival.org/plaza

  ![Screenshot of Firefox opening schedule.mozillafestival.org/plaza website, but showing the extension's settings page instead](https://github.com/jcoyle37/URL-Throttler-2024/assets/2021487/65218733-0add-4091-939d-4e2a988fb329)

**Comment by Lesik** [comment]
- #### https://teams.microsoft.com
  ![Screenshot from 2024-07-03 11-45-33](https://github.com/jcoyle37/URL-Throttler-2024/assets/2021487/efd3151b-5c9c-4ddd-9a09-d83925e02534)
- #### https://npmjs.com
  ![Screenshot from 2024-07-03 16-45-06](https://github.com/jcoyle37/URL-Throttler-2024/assets/2021487/ed9ee334-2c58-4fa0-a9e8-5eb6e6d99ce0)

**Comment by jcoyle37** [comment]
Hi @Lesik , I'm noticing the same behavior from the extension when installed from the Firefox Add-On store. However, when I load as temporary add-on from source code, it works 100% as expected. Which way are you running it?

**Comment by jcoyle37** [comment]
Thank you for catching this @Lesik . Turns out I had the wrong script specified in the manifest. Reference:

* PR #2
* PR #4
